<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function getPagination($page, $maxperpage)
    {
        $q = $this->_em->createQueryBuilder()
            ->select('post')
            ->from('AppBundle:Post', 'post')
            ->where('post.public = :active')->setParameter('active', true);

        $q->setFirstResult(($page-1) * $maxperpage)->setMaxResults($maxperpage);

        $q->orderBy('post.id', 'DESC');

        return new Paginator($q);
    }

    /**
     * @return mixed
     */
    public function getNb()
    {
        return $this->createQueryBuilder('p')
            ->select('COUNT(p)')
            ->getQuery()
            ->getSingleScalarResult();
    }
}
