parameters:
services:
    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }

    file.manager.image:
        class: AppBundle\FileManager\FileManagerImage

    my.listener:
        class: AppBundle\EventListener\ExampleListener
        tags:
            - { name: doctrine.event_listener, event: postPersist }
